// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaUBS.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MinhaUBS.API.Migrations
{
    [DbContext(typeof(MinhaUBSContext))]
    partial class MinhaUBSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("MinhaUBS.API.Models.Funcionario", b =>
                {
                    b.Property<int>("ID_Funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Especialidade")
                        .HasColumnType("text");

                    b.Property<int?>("ID_Unidade1")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.HasKey("ID_Funcionario");

                    b.HasIndex("ID_Unidade1");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("MinhaUBS.API.Models.Servico", b =>
                {
                    b.Property<int>("ID_Servico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeID_Unidade")
                        .HasColumnType("integer");

                    b.HasKey("ID_Servico");

                    b.HasIndex("UnidadeID_Unidade");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("MinhaUBS.API.Models.Unidade", b =>
                {
                    b.Property<int>("ID_Unidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Localizacao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("ID_Unidade");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("MinhaUBS.API.Models.Vacina", b =>
                {
                    b.Property<int>("ID_Vacina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeID_Unidade")
                        .HasColumnType("integer");

                    b.HasKey("ID_Vacina");

                    b.HasIndex("UnidadeID_Unidade");

                    b.ToTable("Vacina");
                });

            modelBuilder.Entity("MinhaUBS.API.Models.Funcionario", b =>
                {
                    b.HasOne("MinhaUBS.API.Models.Unidade", "ID_Unidade")
                        .WithMany()
                        .HasForeignKey("ID_Unidade1");

                    b.Navigation("ID_Unidade");
                });

            modelBuilder.Entity("MinhaUBS.API.Models.Servico", b =>
                {
                    b.HasOne("MinhaUBS.API.Models.Unidade", null)
                        .WithMany("Servicos")
                        .HasForeignKey("UnidadeID_Unidade");
                });

            modelBuilder.Entity("MinhaUBS.API.Models.Vacina", b =>
                {
                    b.HasOne("MinhaUBS.API.Models.Unidade", null)
                        .WithMany("Vacinas")
                        .HasForeignKey("UnidadeID_Unidade");
                });

            modelBuilder.Entity("MinhaUBS.API.Models.Unidade", b =>
                {
                    b.Navigation("Servicos");

                    b.Navigation("Vacinas");
                });
#pragma warning restore 612, 618
        }
    }
}
